# don't copy this, this is for self-testing only
# see the README for how to use this action

on:
  pull_request:
  push:
    branches: [main, test-me-*]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - uses: pre-commit/action@v3.0.0
    # don't copy this, this is for self-testing only
    # see the README for how to use this action
    - uses: ./.
      name: Run pre-commit-ci/lite-action@v1.1.0
      if: always()
